version: '3.7'

services:
  surfsharekit-frontend:
    container_name: surfsharekit-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true