version: '3.7'
services:
  silverstripe-8.3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SS_DATABASE_CLASS: MySQLDatabase
      SS_DATABASE_NAME: silverstripe
      SS_DATABASE_SERVER: database
      SS_DATABASE_USERNAME: root
      SS_DATABASE_PASSWORD: silverstripe
      SS_DEFAULT_ADMIN_USERNAME: ${SS_DEFAULT_ADMIN_USERNAME}
      SS_DEFAULT_ADMIN_PASSWORD: ${SS_DEFAULT_ADMIN_PASSWORD}
      SS_ENVIRONMENT_TYPE: dev
      APPLICATION_ENVIRONMENT: local
      SS_BASE_URL: http://localhost:8080
    links:
      - database
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  database:
    image: mariadb:10
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: silverstripe
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:8.4-alpine
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
  db-data:
  redis-data: