<?php

namespace cms;

use SilverStripe\Admin\CMSMenu;
use SilverStripe\Admin\CMSMenuItem;
use SilverStripe\Dev\FunctionalTest;
use SilverStripe\ORM\DB;
use SurfSharekit\Models\Person;

class CMSFunctionalTest extends FunctionalTest {

    public function __construct(?string $name = null, array $data = [], $dataName = '') {
//        $_GET['flush'] = 1;
        parent::__construct($name, $data, $dataName);
//        $_GET['flush'] = 0;
    }

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        DB::get_conn()->transactionStart();
    }

    public function tearDown(): void {
        parent::tearDown();

        DB::get_conn()->transactionRollback();
    }

    public function testAdmin() {
        ini_set("memory_limit", -1);
        ini_set('max_execution_time', 3600);
        $this->logInWithPermission("ADMIN");
        $this->doAdminWalk();
    }

    private $output = "";
    private function print($string) {
        $this->output .= $string;
        echo $string;
    }
    private function println($string) {
        $this->output .= $string . "\n";
        echo $string . "\n";
    }

    private $hrefList = [];

    private function checkUrl($href) {
        if (str_contains($href, "Security/logout")) {
            // Breaks remaining calls
            return false;
        }
        if (str_starts_with($href, "#")) {
            // Not a true url
            return false;
        }
        if (str_starts_with($href, "/")) {
            $href = substr($href, 1);
        }
        $href = explode("?", $href)[0];

        if ($this->hrefList[$href] ?? false) {
            // Already checked url
            return false;
        }

        $this->hrefList[$href] = true;
        return $href;
    }

    private function checkAllPageLinks($prefix, $level = 1) {
        if ($level > 7) return;

        $i = 0;
        $items = $this->cssParser()->getBySelector("a");
        foreach ($items as $item) {
            $href = (string)$item->attributes()["href"];
            if ($href && $href != "#") {
                if (!str_contains($href, $prefix)) continue;
                if (!$href = $this->checkUrl($href)) continue;
                $i++;
                for ($ii = 0; $ii < $level; $ii++) $this->print("\t");
                $this->println($href);
                $this->get($href);
                $this->checkAllPageLinks($prefix, $level + 1);

                if ($i >= 5) return;
            }
        }
    }

    /**
     * This function walks through the entire CMS and tries every action that's available to it
     */
    public function doAdminWalk() {
        ini_set("output_buffering", "off");
        ob_implicit_flush();
        ob_end_flush();
        $adminList = CMSMenu::get_viewable_menu_items();
        foreach ($adminList as $item) {
            $this->println("--------------------------");
            $this->println("Loading admin " . $item->title . " (" . $item->url . ")");
            $this->get($item->url);
            $this->checkAllPageLinks($item->url);
        }

        ob_start();
    }
}